name: Create Service Principal

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  create-service-principal:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Service Principal
        id: create_sp
        env:
          AZURE_SUBSCRIPTION: ${{ vars.AZURE_SUBSCRIPTION }} # Fetch AZURE_SUBSCRIPTION from GitHub Actions variable
        run: |
          sp_output=$(az ad sp create-for-rbac --name "CopilotAgentDeploy" --role Contributor --scopes /subscriptions/$AZURE_SUBSCRIPTION --output json)
          sp_appId=$(echo $sp_output | jq -r '.appId')
          echo "SP_APP_ID=$sp_appId" >> $GITHUB_ENV
          echo "Service Principal ID: $sp_appId"

      - name: Add and Grant Permissions
        env:
          SP_APP_ID: ${{ env.SP_APP_ID }}
        run: |
          az ad app permission add --id $SP_APP_ID --api 00000003-0000-0000-c000-000000000000 --api-permissions 74ef0291-ca83-4d02-8c7e-d2391e6a444f=Role
          az ad app permission grant --id $SP_APP_ID --api 00000003-0000-0000-c000-000000000000 --scope Role
          az ad app permission add --id $SP_APP_ID --api 00000003-0000-0000-c000-000000000000 --api-permissions eb6b3d76-ed75-4be6-ac36-158d04c0a555=Role
          az ad app permission grant --id $SP_APP_ID --api 00000003-0000-0000-c000-000000000000 --scope Role

