name: Deploy Message Center Agent

on:
  # push:
    # branches: [ main ]
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          
      - name: Package app
        run: |
          cd appPackage
          # Create a ZIP archive of the app
          zip -r ../message-center-agent.zip .
          echo "App packaged successfully"
          
      - name: Generate deployment documentation
        run: |
          # Create a deployment instructions file
          cat > DEPLOYMENT.md << EOF
          # Message Center Agent Deployment Instructions
          
          ## Package Contents
          This package contains the Message Center Agent for Microsoft Teams.
          
          ## Manual Deployment Steps
          1. Download the \`message-center-agent.zip\` package
          2. Use Developer Portal for Microsoft Teams to upload the app package
          3. Add the app to your Teams environment
          
          ## Configuration
          - Configure your admin settings in the Teams Admin Center
          - Ensure your account has appropriate Microsoft Graph permissions for message center access
          EOF
          
      - uses: actions/upload-artifact@main
        with:
          name: message-center-agent
          path: |
            message-center-agent.zip
            DEPLOYMENT.md
          retention-days: 30
          
      - name: Output Deployment Details
        run: |
          echo "Message Center Agent packaged successfully!"
          echo "Download the artifact from the Actions tab to deploy manually to Microsoft Teams"
